{% set name = "cxxfilt" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef6810e76d16c95c11b96371e2d8eefd1d270ec03f9bcd07590e8dcc2c69e92b

build:
  number: 2
  script: '{{ PYTHON }} -m pip install . -vv '
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - cxxfilt

about:
  home: https://github.com/afg984/python-cxxfilt
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python interface to c++filt / abi::__cxa_demangle
  doc_url: https://pypi.org/project/cxxfilt/
  dev_url: https://github.com/afq984/python-cxxfilt

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
